pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}

dependencyResolutionManagement {
    repositories { mavenCentral() }
}

includeBuild("build-logic")

rootProject.name = 'log-stream-alert-system'

include(
    "log-stream-biz-standardizer",
    "log-stream-common",
    "log-stream-mock-service",
    "log-stream-logging-service"
)
include 'log-stream-logging-service:Annotation-Processor'