spring.profiles.active=prod

kafka.bootstrap-servers=broker1:9092,broker2:9092
kafka.log-topic=your-log-topic
kafka.acks=1
kafka.key-serializer=org.apache.kafka.common.serialization.StringSerializer
kafka.value-serializer=org.apache.kafka.common.serialization.StringSerializer
