## Common Setting
spring.application.name=common
spring.profiles.active=dev
service.name=common
## Actuator Setting
# actuator endpoint Activate
management.endpoints.web.exposure.include=health,metrics,prometheus
# actuator base path
management.endpoints.web.base-path=/actuator
# health Detail information expose
management.endpoint.health.show-details=always
# Prometheus export Activate
management.metrics.export.prometheus.enabled=true
# Actuator Call Scheduler Option
monitoring.scheduler.enable=true
## WebClient Setting
# Monitoring Connection Timeout (second)
monitoring.timeout.connect=3
# Monitoring request Timeout (second)
monitoring.timeout.read=3
# Actuator Call Interval (ms)
monitoring.scheduler.interval.ms=10000