global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'mock-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']
    relabel_configs:
      - source_labels: [ __address__ ]
        target_label: instance
        replacement: 'mock-service'
    scheme: http
    http_headers:
      # Prometheus가 Actuator에서 데이터를 가져오려면 세팅해야하는 헤더값
      X-Monitoring-Token:
        values: [ "test-token" ]
      # mockup 서비스를 호출하는 모든 요소는 해당 헤더를 가지고 있어야함(보안정책)
      X-Auth-Token:
        values: [ "test-token" ]