## Common Setting
spring.application.name=mock-service
service.name=mockup
# Use Logging Interceptor
logging.interceptor.enabled=true
## Actuator Setting
# actuator endpoint Activate
management.endpoints.web.exposure.include=health,prometheus
# actuator base path
management.endpoints.web.base-path=/actuator
# health Detail information expose
management.endpoint.health.show-details=always
# Prometheus export Activate
management.metrics.export.prometheus.enabled=true
# Actuator Call Scheduler Option
monitoring.scheduler.enable=true
## WebClient Setting
# Monitoring Connection Timeout (second)
monitoring.timeout.connect=PT3S
# Monitoring request Timeout (second)
monitoring.timeout.read=PT3S
# Actuator Call Interval (ms)
monitoring.scheduler.interval.ms=10000