kafka.bootstrap-servers=localhost:9092
kafka.log-topic=dummy-log-topic
kafka.acks=1
kafka.key-serializer=org.apache.kafka.common.serialization.StringSerializer
kafka.value-serializer=org.apache.kafka.common.serialization.StringSerializer

