plugins {
	id 'java'
	id 'org.springframework.boot' version '3.4.4' apply false
	id 'io.spring.dependency-management' version '1.1.7'
}

description = '''\
Shared utility and base components for alerting system. Includes DTOs, constants, exceptions, and common interfaces.
(알림 시스템을 위한 공용 유틸리티 및 기반 컴포넌트. DTO, 상수, 예외, 공통 인터페이스를 포함)
'''

dependencies {
	// prometheus를 이용하여 application health를 체크하기 위한 dependency
	implementation 'org.springframework.boot:spring-boot-starter-actuator'
	// log를 찍을때, json 형식으로 찍히도록 처리하는 dependency
	implementation "net.logstash.logback:logstash-logback-encoder:${logstashEncoderVersion}"
	// AOP 전용 모듈
	implementation 'org.springframework.boot:spring-boot-starter-aop'
	// Web core (tomcat 없이 web 기능만)
	implementation 'org.springframework:spring-webmvc'
	// http servlet용
	implementation  "jakarta.servlet:jakarta.servlet-api:${jakartaServletApiVersion}"
	// 테스트에서만 Spring Boot Web 서버 환경 사용
	testImplementation 'org.springframework.boot:spring-boot-starter-web'
}