plugins {
    id 'java'
}

description = '''\
Central log processor that stores logs and triggers alerts for critical events
(Kafka에서 로그를 수신하고, 영속 저장소에 저장하며, 영속성 데이터 베이스 )
'''

dependencies {
    // 전체 프로젝트에서 공통적으로 사용되는 로그 구조 같은 요소들을 모아넣은 project
    implementation project(':log-stream-common')

    // PostgreSQL용 client 코드 필요
//    implementation "com.scylladb:java-driver-core:${scyllaDBVersion}"
//    implementation "com.scylladb:java-driver-query-builder:${scyllaDBVersion}"
//    implementation "com.scylladb:java-driver-mapper-runtime:${scyllaDBVersion}"
//    annotationProcessor "com.scylladb:java-driver-mapper-processor:${scyllaDBVersion}"

    // 메시지 수신용 springboot와 연관 없는 kafka client 필요
//    implementation 'org.springframework.kafka:spring-kafka'
//
//    testImplementation 'org.springframework.boot:spring-boot-starter-test'
//    testImplementation 'org.springframework.kafka:spring-kafka-test'
//
//    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}
