plugins {
    id 'java'
}

description = '''\
Central log processor that stores logs and triggers alerts for critical events
(Kafka에서 로그를 수신하고, 영속 저장소에 저장하며, 영속성 데이터 베이스 )
'''

dependencies {
    // 전체 프로젝트에서 공통적으로 사용되는 로그 구조 같은 요소들을 모아넣은 project
    implementation project(':log-stream-common')

    implementation "org.apache.kafka:kafka-clients:${kafkaClientsVersion}"
    implementation "org.postgresql:postgresql:${postgresqlClientsVersion}"
    implementation "com.zaxxer:HikariCP:${hikariCpVersion}"
    implementation "com.fasterxml.jackson.core:jackson-databind:${jacksonDatabindVersion}"
    implementation "org.slf4j:slf4j-api:${log4jVersion}"
    implementation "org.apache.logging.log4j:log4j-slf4j-impl:${log4jVersion}"
    implementation "org.apache.logging.log4j:log4j-core:${log4jVersion}"

    // annotation scan 후 적절한 class 찾아주는 용도
    implementation "io.github.classgraph:classgraph:${classPathScannerVersion}"

    // 효율적으로 Map을 Json 메시지로 직렬화 시켜주는 라이브러리
    implementation "com.github.fmjsjx:libcommon-json-jsoniter:${jsoniterVersion}"

    runtimeOnly "ch.qos.logback:logback-classic:${logbackVersion}"
}
