plugins {
    id 'java'
    id 'com.no-spring-test-conventions'
}

description = '''\
Central log processor that stores logs and triggers alerts for critical events
(Kafka에서 로그를 수신하고, 처리하고, 영속 저장소에 저장하는 로직을 담은 서비스)
'''

dependencies {
    annotationProcessor project(":log-stream-logging-service:Annotation-Processor")
    testAnnotationProcessor project(":log-stream-logging-service:Annotation-Processor")

    implementation project(":log-stream-logging-service:Annotation-Processor")
    // 전체 프로젝트에서 공통적으로 사용되는 로그 구조 같은 요소들을 모아넣은 project
    implementation project(':log-stream-common')

    // 로그 데이터를 가져오기 위한 kafka client
    implementation "org.apache.kafka:kafka-clients:${kafkaClientsVersion}"
    // 영속성 저장소에 저장하기 위한 postgres 데이터베이스 client
    implementation "org.postgresql:postgresql:${postgresqlClientsVersion}"
    // 영속성 저장소에 저장하기 위해 사용하는 java database interface
    implementation "org.jdbi:jdbi3-core:${jdbiVersion}"
    // Connection Pool 관리를 위한 hikariCP
    implementation "com.zaxxer:HikariCP:${hikariCpVersion}"

    // 로깅을 위한 라이브러리
    implementation "org.slf4j:slf4j-api:${log4jVersion}"
    implementation "org.apache.logging.log4j:log4j-slf4j-impl:${log4jImplVersion}"
    implementation "org.apache.logging.log4j:log4j-core:${log4jImplVersion}"

    // annotation scan 후 적절한 class 찾아주는 용도
    implementation "io.github.classgraph:classgraph:${classPathScannerVersion}"

    runtimeOnly "ch.qos.logback:logback-classic:${logbackVersion}"

    testImplementation "org.mockito:mockito-core:${mockitoVersion}"
    testImplementation "org.mockito:mockito-inline:${mockitoInlineVersion}" // static/final 모킹
}

// 1) 테스트 전용 레지스트리 JAR 생성
def testRegistryJar = tasks.register('testRegistryJar', Jar) {
    archiveBaseName.set('test-registry-override')
    from('src/test/resources-override') {
        // 운영과 동일 경로/파일명으로 넣어 덮어쓰기
        include 'META-INF/rihee/logging/collectors.index'
    }
    // (선택) 재현성 옵션
    // preserveFileTimestamps = false
    // reproducibleFileOrder = true
}

tasks.withType(Test).configureEach {
    useJUnitPlatform()

    dependsOn(testRegistryJar)
    // testRegistryJar 산출물을 classpath 맨 앞에 배치
    classpath = files(testRegistryJar.flatMap { it.archiveFile }) + classpath

    // 환경 변수 설정
//    environment "VALIDATOR_MODE", "strict"
    environment "POSTGRES_CONNECT_PASSWORD", "password"

    // JVM 옵션
    jvmArgs += ["-XX:+EnableDynamicAgentLoading"]
}