plugins {
    id 'java-library'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation project(':log-stream-logging-service')

    implementation 'com.google.auto.service:auto-service:1.1.1'
    annotationProcessor 'com.google.auto.service:auto-service:1.1.1'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21) // 프로젝트에 맞춰서
    }
}

test {
    useJUnitPlatform()
}