plugins {
    id 'java'
    id 'org.springframework.boot' version '3.5.0'
    id 'io.spring.dependency-management' version '1.1.7'
}

description = '''\
Mock service that simulates log-generating applications for testing the distributed alerting system.
(Mock 서비스를 위한 로그 발생기)
'''

dependencies {
    implementation project(':log-stream-common')

    implementation 'org.springframework.boot:spring-boot-starter-web'

    // WebClient 전용 (자체 service call용)
    implementation 'org.springframework.boot:spring-boot-starter-webflux'
    // 보안을 위한 dependency
    implementation 'org.springframework.boot:spring-boot-starter-security'
    // 파라미터 Validation을 위한 dependency
    implementation 'org.springframework.boot:spring-boot-starter-validation'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'

    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

// 테스트 코드 전용 java 옵션, 환경변수 세팅
test {
    useJUnitPlatform()
    systemProperty "service.name", "mockup"
    systemProperty "spring.profiles.active", "dev"
    environment "HOST", "localhost"
    environment "CONTAINER", "local-container"
    environment "monitoring.token", "test-token"
    environment "mockup.token", "test-token"
    jvmArgs += ["-XX:+EnableDynamicAgentLoading"]
}